/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AwardImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "award.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SubjectOption = {
  _type: "subjectOption";
  value?: string;
  label?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "linkedin" | "facebook" | "instagram" | "youtube";
  href?: string;
  label?: string;
};

export type FooterLink = {
  _type: "footerLink";
  label?: string;
  href?: string;
  target?: "_self" | "_blank";
  rel?: string;
};

export type NavChild = {
  _type: "navChild";
  label?: string;
  href?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavChild
  >;
};

export type PostTable = {
  _type: "postTable";
  caption?: string;
  hasHeader?: boolean;
  rows?: Array<{
    cells?: Array<string>;
    _type: "row";
    _key: string;
  }>;
};

export type PostQuote = {
  _type: "postQuote";
  text?: string;
  author?: string;
};

export type PostImage = {
  _type: "postImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  legacySrc?: string;
  alt?: string;
  caption?: string;
  width?: number;
  height?: number;
};

export type PostBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5";
      listItem?: "bullet" | "number" | "statements";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & PostImage)
  | ({
      _key: string;
    } & PostQuote)
  | ({
      _key: string;
    } & PostTable)
>;

export type ClientLogo = {
  _type: "clientLogo";
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type Testimonial = {
  _type: "testimonial";
  category?: string;
  quote?: string;
  position?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  audioSrc?: string;
};

export type ReportSlide = {
  _type: "reportSlide";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type ReportHighlight = {
  _type: "reportHighlight";
  title?: string;
};

export type TeamHighlight = {
  _type: "teamHighlight";
  value?: string;
  description?: string;
  cta?: LinkCta;
};

export type TeamBatch = {
  _type: "teamBatch";
  members?: Array<
    {
      _key: string;
    } & TeamMember
  >;
};

export type TeamMember = {
  _type: "teamMember";
  name?: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  from?: string;
  to?: string;
};

export type ArticleTeaser = {
  _type: "articleTeaser";
  href?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  tag?: string;
  title?: string;
  date?: string;
};

export type CaseStudySlide = {
  _type: "caseStudySlide";
  label?: string;
  bg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  previewVideo?: string;
  video?: string;
};

export type LinkCta = {
  _type: "linkCta";
  label?: string;
  href?: string;
  target?: "_self" | "_blank";
};

export type GrowthStat = {
  _type: "growthStat";
  stat?: string;
  description?: string;
};

export type GrowthCard = {
  _type: "growthCard";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoSrc?: string;
  alt?: string;
  label?: string;
  description?: string;
};

export type ServiceItem = {
  _type: "serviceItem";
  href?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  overlayColor?: string;
};

export type HeroBanner = {
  _type: "heroBanner";
  title?: string;
  subtitle?: string;
  description?: string;
  videoSrc?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  posterSrc?: string;
  animateSpin?: boolean;
};

export type TeamSection = {
  _type: "teamSection";
  title?: string;
  batches?: Array<
    {
      _key: string;
    } & TeamBatch
  >;
  highlight?: TeamHighlight;
};

export type GrowthValidationSection = {
  _type: "growthValidationSection";
  title?: string;
  sectionLink?: string;
  eyebrow?: string;
  headline?: string;
  awards?: Array<{
    href?: string;
    image?: AwardImage;
    alt?: string;
    _type: "award";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt?: string;
};

export type TestimonialsSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonialsSection";
};

export type TestimonialsBlock = {
  _type: "testimonialsBlock";
  source?: TestimonialsSectionReference;
};

export type ArticleCardsSection = {
  _type: "articleCardsSection";
  title?: string;
  sectionLink?: string;
  articles?: Array<
    {
      _key: string;
    } & ArticleTeaser
  >;
};

export type CaseStudySection = {
  _type: "caseStudySection";
  slides?: Array<
    {
      _key: string;
    } & CaseStudySlide
  >;
};

export type UnrivaledGrowthSection = {
  _type: "unrivaledGrowthSection";
  title?: string;
  stats?: Array<
    {
      _key: string;
    } & GrowthStat
  >;
  cta?: LinkCta;
};

export type GrowthSpurtsSection = {
  _type: "growthSpurtsSection";
  cards?: Array<
    {
      _key: string;
    } & GrowthCard
  >;
};

export type ServicesSection = {
  _type: "servicesSection";
  services?: Array<
    {
      _key: string;
    } & ServiceItem
  >;
};

export type HeroSection = {
  _type: "heroSection";
  hero?: HeroBanner;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoAlt?: string;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerHeadline?: string;
  footerHeadlineAccent?: string;
  footerCta?: LinkCta;
  exploreTitle?: string;
  exploreLinks?: Array<
    {
      _key: string;
    } & FooterLink
  >;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  newsletterTitle?: string;
  newsletterLabel?: string;
  newsletterPlaceholder?: string;
  newsletterSubmitLabel?: string;
  newsletterRequiredMessage?: string;
  newsletterInvalidMessage?: string;
  copyright?: string;
  legalLinks?: Array<
    {
      _key: string;
    } & FooterLink
  >;
  siteName?: string;
  siteUrl?: string;
  defaultTitle?: string;
  titleTemplate?: string;
  defaultDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImageAlt?: string;
  googleSiteVerification?: string;
  contactTitle?: string;
  contactMetaTitle?: string;
  contactMetaDescription?: string;
  contactFieldPlaceholders?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
  contactSubjectLabel?: string;
  contactSubjectPlaceholder?: string;
  contactSubjectOptions?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
  contactConsentText?: string;
  contactConsentLinkLabel?: string;
  contactConsentLinkHref?: string;
  contactSubmitLabel?: string;
  contactSuccessMessage?: string;
  contactMessagePlaceholder?: string;
  contactMarketingLabel?: string;
  contactTermsLabel?: string;
  contactValidationMessages?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
  postListingTitle?: string;
  postListingHeading?: string;
  postListingDescription?: string;
  reportFormTitle?: string;
  reportFormSubmitLabel?: string;
  reportFormSuccessMessage?: string;
  reportFormPrivacyHref?: string;
  reportFormMarketingLabel?: string;
  reportFormConsentText?: string;
  reportFormConsentLinkLabel?: string;
  reportFormFieldLabels?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
  reportFormValidationMessages?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TestimonialsSection = {
  _id: string;
  _type: "testimonialsSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  categories?: Array<string>;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  logos?: Array<
    {
      _key: string;
    } & ClientLogo
  >;
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  heroBannerData?: HeroBanner;
  reportHighlights?: Array<
    {
      _key: string;
    } & ReportHighlight
  >;
  reportSlides?: Array<
    {
      _key: string;
    } & ReportSlide
  >;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  href?: string;
  subtitle?: string;
  authorName?: string;
  category?: string;
  publishDate?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featuredImageSrc?: string;
  content?: PostBody;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & ServicesSection)
    | ({
        _key: string;
      } & GrowthSpurtsSection)
    | ({
        _key: string;
      } & UnrivaledGrowthSection)
    | ({
        _key: string;
      } & CaseStudySection)
    | ({
        _key: string;
      } & ArticleCardsSection)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & GrowthValidationSection)
    | ({
        _key: string;
      } & TeamSection)
  >;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AwardImage
  | Seo
  | SubjectOption
  | SocialLink
  | FooterLink
  | NavChild
  | NavLink
  | PostTable
  | PostQuote
  | PostImage
  | PostBody
  | ClientLogo
  | Testimonial
  | ReportSlide
  | ReportHighlight
  | TeamHighlight
  | TeamBatch
  | TeamMember
  | ArticleTeaser
  | CaseStudySlide
  | LinkCta
  | GrowthStat
  | GrowthCard
  | ServiceItem
  | HeroBanner
  | TeamSection
  | GrowthValidationSection
  | TestimonialsSectionReference
  | TestimonialsBlock
  | ArticleCardsSection
  | CaseStudySection
  | UnrivaledGrowthSection
  | GrowthSpurtsSection
  | ServicesSection
  | HeroSection
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | TestimonialsSection
  | Report
  | Slug
  | Article
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: queries/article.ts
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{  "slug": slug.current,  category,  title,  authorName,  publishDate,  "featuredImage": coalesce(featuredImage.asset->url, featuredImageSrc),  content[]{    ...,    _type == "postImage" => {      _key,      _type,      alt,      caption,      "src": coalesce(image.asset->url, legacySrc),      "width": coalesce(image.asset->metadata.dimensions.width, width),      "height": coalesce(image.asset->metadata.dimensions.height, height)    },    _type == "block" => { ..., markDefs[]{ ... } }  }}
export type ARTICLE_QUERY_RESULT = {
  slug: string | null;
  category: string | null;
  title: string | null;
  authorName: string | null;
  publishDate: string | null;
  featuredImage: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "h4" | "h5" | "normal";
        listItem?: "bullet" | "number" | "statements";
        markDefs: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "postImage";
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        legacySrc?: string;
        alt: string | null;
        caption: string | null;
        width: number | null;
        height: number | null;
        src: string | null;
      }
    | {
        _key: string;
        _type: "postQuote";
        text?: string;
        author?: string;
      }
    | {
        _key: string;
        _type: "postTable";
        caption?: string;
        hasHeader?: boolean;
        rows?: Array<{
          cells?: Array<string>;
          _type: "row";
          _key: string;
        }>;
      }
  > | null;
} | null;

// Source: queries/article.ts
// Variable: ARTICLE_EXISTS_QUERY
// Query: count(*[_type == "article" && slug.current == $slug && count(content) > 0]) > 0
export type ARTICLE_EXISTS_QUERY_RESULT = boolean;

// Source: queries/articles.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"] | order(order asc) [$start...$end]{  "slug": slug.current,  href,  "imgSrc": coalesce(featuredImage.asset->url, featuredImageSrc),  title,  subtitle,  authorName}
export type ARTICLES_QUERY_RESULT = Array<{
  slug: string | null;
  href: string | null;
  imgSrc: string | null;
  title: string | null;
  subtitle: string | null;
  authorName: string | null;
}>;

// Source: queries/articles.ts
// Variable: ARTICLES_COUNT_QUERY
// Query: count(*[_type == "article"])
export type ARTICLES_COUNT_QUERY_RESULT = number;

// Source: queries/articles.ts
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[_type == "article" && defined(slug.current) && count(content) > 0].slug.current
export type ARTICLE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: queries/page.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  "slug": slug.current,  title,  sections[]{    _key,    _type,    _type == "heroSection" => {      hero{        title, subtitle, description, videoSrc, animateSpin,        "posterSrc": coalesce(poster.asset->url, posterSrc)      }    },    _type == "servicesSection" => {      services[]{ href, "imgSrc": image.asset->url, alt, overlayColor }    },    _type == "growthSpurtsSection" => {      cards[]{ "id": _key, "imageSrc": image.asset->url, videoSrc, alt, label, description }    },    _type == "unrivaledGrowthSection" => {      title,      stats[]{ "id": _key, stat, description },      cta{ label, href }    },    _type == "caseStudySection" => {      slides[]{ "id": _key, label, "bg": bg.asset->url, previewVideo, video }    },    _type == "articleCardsSection" => {      title,      sectionLink,      articles[]{ href, "imgSrc": image.asset->url, alt, tag, title, date }    },    _type == "testimonialsBlock" => {      "data": source->{        title,        categories,        testimonials[]{          "id": _key, category, audioSrc,          "imgSrc": image.asset->url, alt, quote, position        },        logos[]{ "id": _key, "src": logo.asset->url, alt }      }    },    _type == "growthValidationSection" => {      title,      sectionLink,      eyebrow,      headline,      awards[]{ href, "image": image.asset->url, alt },      "image": image.asset->url,      imageAlt    },    _type == "teamSection" => {      title,      batches[]{ members[]{ name, title, from, to, "image": image.asset->url } },      highlight{ value, description, cta{ label, href, target } }    }  }}
export type PAGE_QUERY_RESULT = {
  slug: string | null;
  title: string | null;
  sections: Array<
    | {
        _key: string;
        _type: "articleCardsSection";
        title: string | null;
        sectionLink: string | null;
        articles: Array<{
          href: string | null;
          imgSrc: string | null;
          alt: string | null;
          tag: string | null;
          title: string | null;
          date: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "caseStudySection";
        slides: Array<{
          id: string;
          label: string | null;
          bg: string | null;
          previewVideo: string | null;
          video: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "growthSpurtsSection";
        cards: Array<{
          id: string;
          imageSrc: string | null;
          videoSrc: string | null;
          alt: string | null;
          label: string | null;
          description: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "growthValidationSection";
        title: string | null;
        sectionLink: string | null;
        eyebrow: string | null;
        headline: string | null;
        awards: Array<{
          href: string | null;
          image: string | null;
          alt: string | null;
        }> | null;
        image: string | null;
        imageAlt: string | null;
      }
    | {
        _key: string;
        _type: "heroSection";
        hero: {
          title: string | null;
          subtitle: string | null;
          description: string | null;
          videoSrc: string | null;
          animateSpin: boolean | null;
          posterSrc: string | null;
        } | null;
      }
    | {
        _key: string;
        _type: "servicesSection";
        services: Array<{
          href: string | null;
          imgSrc: string | null;
          alt: string | null;
          overlayColor: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "teamSection";
        title: string | null;
        batches: Array<{
          members: Array<{
            name: string | null;
            title: string | null;
            from: string | null;
            to: string | null;
            image: string | null;
          }> | null;
        }> | null;
        highlight: {
          value: string | null;
          description: string | null;
          cta: {
            label: string | null;
            href: string | null;
            target: "_blank" | "_self" | null;
          } | null;
        } | null;
      }
    | {
        _key: string;
        _type: "testimonialsBlock";
        data: {
          title: string | null;
          categories: Array<string> | null;
          testimonials: Array<{
            id: string;
            category: string | null;
            audioSrc: string | null;
            imgSrc: string | null;
            alt: string | null;
            quote: string | null;
            position: string | null;
          }> | null;
          logos: Array<{
            id: string;
            src: string | null;
            alt: string | null;
          }> | null;
        } | null;
      }
    | {
        _key: string;
        _type: "unrivaledGrowthSection";
        title: string | null;
        stats: Array<{
          id: string;
          stat: string | null;
          description: string | null;
        }> | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
      }
  > | null;
} | null;

// Source: queries/reports.ts
// Variable: REPORTS_QUERY
// Query: *[_type == "report"]{  "slug": slug.current,  heroBannerData{    title, subtitle, description, videoSrc, animateSpin,    "posterSrc": coalesce(poster.asset->url, posterSrc)  },  reportHighlights[]{ "id": _key, title },  reportSlides[]{ "id": _key, "src": image.asset->url, alt }}
export type REPORTS_QUERY_RESULT = Array<{
  slug: string | null;
  heroBannerData: {
    title: string | null;
    subtitle: string | null;
    description: string | null;
    videoSrc: string | null;
    animateSpin: boolean | null;
    posterSrc: string | null;
  } | null;
  reportHighlights: Array<{
    id: string;
    title: string | null;
  }> | null;
  reportSlides: Array<{
    id: string;
    src: string | null;
    alt: string | null;
  }> | null;
}>;

// Source: queries/reports.ts
// Variable: REPORT_QUERY
// Query: *[_type == "report" && slug.current == $slug][0]{  "slug": slug.current,  heroBannerData{    title, subtitle, description, videoSrc, animateSpin,    "posterSrc": coalesce(poster.asset->url, posterSrc)  },  reportHighlights[]{ "id": _key, title },  reportSlides[]{ "id": _key, "src": image.asset->url, alt }}
export type REPORT_QUERY_RESULT = {
  slug: string | null;
  heroBannerData: {
    title: string | null;
    subtitle: string | null;
    description: string | null;
    videoSrc: string | null;
    animateSpin: boolean | null;
    posterSrc: string | null;
  } | null;
  reportHighlights: Array<{
    id: string;
    title: string | null;
  }> | null;
  reportSlides: Array<{
    id: string;
    src: string | null;
    alt: string | null;
  }> | null;
} | null;

// Source: queries/reports.ts
// Variable: REPORT_SLUGS_QUERY
// Query: *[_type == "report" && defined(slug.current)].slug.current
export type REPORT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  "logo": logo.asset->url,  logoAlt,  navLinks[]{ label, href, children[]{ label, href } },  footerHeadline,  footerHeadlineAccent,  footerCta{ label, href },  exploreTitle,  exploreLinks[]{ label, href, target, rel },  socials[]{ platform, href, label },  newsletterTitle,  newsletterLabel,  newsletterPlaceholder,  newsletterSubmitLabel,  newsletterRequiredMessage,  newsletterInvalidMessage,  copyright,  legalLinks[]{ label, href, target, rel },  siteName,  siteUrl,  defaultTitle,  titleTemplate,  defaultDescription,  "ogImage": ogImage.asset->url,  "ogImageWidth": ogImage.asset->metadata.dimensions.width,  "ogImageHeight": ogImage.asset->metadata.dimensions.height,  ogImageAlt,  googleSiteVerification,  contactTitle,  contactMetaTitle,  contactMetaDescription,  contactFieldPlaceholders[]{ value, label },  contactSubjectLabel,  contactSubjectPlaceholder,  contactSubjectOptions[]{ value, label },  contactConsentText,  contactConsentLinkLabel,  contactConsentLinkHref,  contactSubmitLabel,  contactSuccessMessage,  contactMessagePlaceholder,  contactMarketingLabel,  contactTermsLabel,  contactValidationMessages[]{ value, label },  postListingTitle,  postListingHeading,  postListingDescription,  reportFormTitle,  reportFormSubmitLabel,  reportFormSuccessMessage,  reportFormPrivacyHref,  reportFormMarketingLabel,  reportFormConsentText,  reportFormConsentLinkLabel,  reportFormFieldLabels[]{ value, label },  reportFormValidationMessages[]{ value, label }}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      logo: null;
      logoAlt: null;
      navLinks: null;
      footerHeadline: null;
      footerHeadlineAccent: null;
      footerCta: null;
      exploreTitle: null;
      exploreLinks: null;
      socials: null;
      newsletterTitle: null;
      newsletterLabel: null;
      newsletterPlaceholder: null;
      newsletterSubmitLabel: null;
      newsletterRequiredMessage: null;
      newsletterInvalidMessage: null;
      copyright: null;
      legalLinks: null;
      siteName: null;
      siteUrl: null;
      defaultTitle: null;
      titleTemplate: null;
      defaultDescription: null;
      ogImage: null;
      ogImageWidth: null;
      ogImageHeight: null;
      ogImageAlt: null;
      googleSiteVerification: null;
      contactTitle: null;
      contactMetaTitle: null;
      contactMetaDescription: null;
      contactFieldPlaceholders: null;
      contactSubjectLabel: null;
      contactSubjectPlaceholder: null;
      contactSubjectOptions: null;
      contactConsentText: null;
      contactConsentLinkLabel: null;
      contactConsentLinkHref: null;
      contactSubmitLabel: null;
      contactSuccessMessage: null;
      contactMessagePlaceholder: null;
      contactMarketingLabel: null;
      contactTermsLabel: null;
      contactValidationMessages: null;
      postListingTitle: null;
      postListingHeading: null;
      postListingDescription: null;
      reportFormTitle: null;
      reportFormSubmitLabel: null;
      reportFormSuccessMessage: null;
      reportFormPrivacyHref: null;
      reportFormMarketingLabel: null;
      reportFormConsentText: null;
      reportFormConsentLinkLabel: null;
      reportFormFieldLabels: null;
      reportFormValidationMessages: null;
    }
  | {
      logo: string | null;
      logoAlt: string | null;
      navLinks: Array<{
        label: string | null;
        href: string | null;
        children: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      }> | null;
      footerHeadline: string | null;
      footerHeadlineAccent: string | null;
      footerCta: {
        label: string | null;
        href: string | null;
      } | null;
      exploreTitle: string | null;
      exploreLinks: Array<{
        label: string | null;
        href: string | null;
        target: "_blank" | "_self" | null;
        rel: string | null;
      }> | null;
      socials: Array<{
        platform: "facebook" | "instagram" | "linkedin" | "youtube" | null;
        href: string | null;
        label: string | null;
      }> | null;
      newsletterTitle: string | null;
      newsletterLabel: string | null;
      newsletterPlaceholder: string | null;
      newsletterSubmitLabel: string | null;
      newsletterRequiredMessage: string | null;
      newsletterInvalidMessage: string | null;
      copyright: string | null;
      legalLinks: Array<{
        label: string | null;
        href: string | null;
        target: "_blank" | "_self" | null;
        rel: string | null;
      }> | null;
      siteName: string | null;
      siteUrl: string | null;
      defaultTitle: string | null;
      titleTemplate: string | null;
      defaultDescription: string | null;
      ogImage: string | null;
      ogImageWidth: number | null;
      ogImageHeight: number | null;
      ogImageAlt: string | null;
      googleSiteVerification: string | null;
      contactTitle: string | null;
      contactMetaTitle: string | null;
      contactMetaDescription: string | null;
      contactFieldPlaceholders: Array<{
        value: string | null;
        label: string | null;
      }> | null;
      contactSubjectLabel: string | null;
      contactSubjectPlaceholder: string | null;
      contactSubjectOptions: Array<{
        value: string | null;
        label: string | null;
      }> | null;
      contactConsentText: string | null;
      contactConsentLinkLabel: string | null;
      contactConsentLinkHref: string | null;
      contactSubmitLabel: string | null;
      contactSuccessMessage: string | null;
      contactMessagePlaceholder: string | null;
      contactMarketingLabel: string | null;
      contactTermsLabel: string | null;
      contactValidationMessages: Array<{
        value: string | null;
        label: string | null;
      }> | null;
      postListingTitle: string | null;
      postListingHeading: string | null;
      postListingDescription: string | null;
      reportFormTitle: string | null;
      reportFormSubmitLabel: string | null;
      reportFormSuccessMessage: string | null;
      reportFormPrivacyHref: string | null;
      reportFormMarketingLabel: string | null;
      reportFormConsentText: string | null;
      reportFormConsentLinkLabel: string | null;
      reportFormFieldLabels: Array<{
        value: string | null;
        label: string | null;
      }> | null;
      reportFormValidationMessages: Array<{
        value: string | null;
        label: string | null;
      }> | null;
    }
  | null;

// Source: queries/testimonials.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonialsSection"][0]{  title,  categories,  testimonials[]{    "id": _key, category, audioSrc,    "imgSrc": image.asset->url, alt, quote, position  },  logos[]{ "id": _key, "src": logo.asset->url, alt }}
export type TESTIMONIALS_QUERY_RESULT = {
  title: string | null;
  categories: Array<string> | null;
  testimonials: Array<{
    id: string;
    category: string | null;
    audioSrc: string | null;
    imgSrc: string | null;
    alt: string | null;
    quote: string | null;
    position: string | null;
  }> | null;
  logos: Array<{
    id: string;
    src: string | null;
    alt: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "article" && slug.current == $slug][0]{\n  "slug": slug.current,\n  category,\n  title,\n  authorName,\n  publishDate,\n  "featuredImage": coalesce(featuredImage.asset->url, featuredImageSrc),\n  content[]{\n    ...,\n    _type == "postImage" => {\n      _key,\n      _type,\n      alt,\n      caption,\n      "src": coalesce(image.asset->url, legacySrc),\n      "width": coalesce(image.asset->metadata.dimensions.width, width),\n      "height": coalesce(image.asset->metadata.dimensions.height, height)\n    },\n    _type == "block" => { ..., markDefs[]{ ... } }\n  }\n}': ARTICLE_QUERY_RESULT;
    'count(*[_type == "article" && slug.current == $slug && count(content) > 0]) > 0': ARTICLE_EXISTS_QUERY_RESULT;
    '*[_type == "article"] | order(order asc) [$start...$end]{\n  "slug": slug.current,\n  href,\n  "imgSrc": coalesce(featuredImage.asset->url, featuredImageSrc),\n  title,\n  subtitle,\n  authorName\n}': ARTICLES_QUERY_RESULT;
    'count(*[_type == "article"])': ARTICLES_COUNT_QUERY_RESULT;
    '*[_type == "article" && defined(slug.current) && count(content) > 0].slug.current': ARTICLE_SLUGS_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n  "slug": slug.current,\n  title,\n  sections[]{\n    _key,\n    _type,\n\n    _type == "heroSection" => {\n      hero{\n        title, subtitle, description, videoSrc, animateSpin,\n        "posterSrc": coalesce(poster.asset->url, posterSrc)\n      }\n    },\n\n    _type == "servicesSection" => {\n      services[]{ href, "imgSrc": image.asset->url, alt, overlayColor }\n    },\n\n    _type == "growthSpurtsSection" => {\n      cards[]{ "id": _key, "imageSrc": image.asset->url, videoSrc, alt, label, description }\n    },\n\n    _type == "unrivaledGrowthSection" => {\n      title,\n      stats[]{ "id": _key, stat, description },\n      cta{ label, href }\n    },\n\n    _type == "caseStudySection" => {\n      slides[]{ "id": _key, label, "bg": bg.asset->url, previewVideo, video }\n    },\n\n    _type == "articleCardsSection" => {\n      title,\n      sectionLink,\n      articles[]{ href, "imgSrc": image.asset->url, alt, tag, title, date }\n    },\n\n    _type == "testimonialsBlock" => {\n      "data": source->{\n        title,\n        categories,\n        testimonials[]{\n          "id": _key, category, audioSrc,\n          "imgSrc": image.asset->url, alt, quote, position\n        },\n        logos[]{ "id": _key, "src": logo.asset->url, alt }\n      }\n    },\n\n    _type == "growthValidationSection" => {\n      title,\n      sectionLink,\n      eyebrow,\n      headline,\n      awards[]{ href, "image": image.asset->url, alt },\n      "image": image.asset->url,\n      imageAlt\n    },\n\n    _type == "teamSection" => {\n      title,\n      batches[]{ members[]{ name, title, from, to, "image": image.asset->url } },\n      highlight{ value, description, cta{ label, href, target } }\n    }\n  }\n}': PAGE_QUERY_RESULT;
    '*[_type == "report"]{\n  "slug": slug.current,\n  heroBannerData{\n    title, subtitle, description, videoSrc, animateSpin,\n    "posterSrc": coalesce(poster.asset->url, posterSrc)\n  },\n  reportHighlights[]{ "id": _key, title },\n  reportSlides[]{ "id": _key, "src": image.asset->url, alt }\n}': REPORTS_QUERY_RESULT;
    '*[_type == "report" && slug.current == $slug][0]{\n  "slug": slug.current,\n  heroBannerData{\n    title, subtitle, description, videoSrc, animateSpin,\n    "posterSrc": coalesce(poster.asset->url, posterSrc)\n  },\n  reportHighlights[]{ "id": _key, title },\n  reportSlides[]{ "id": _key, "src": image.asset->url, alt }\n}': REPORT_QUERY_RESULT;
    '*[_type == "report" && defined(slug.current)].slug.current': REPORT_SLUGS_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n  "logo": logo.asset->url,\n  logoAlt,\n  navLinks[]{ label, href, children[]{ label, href } },\n\n  footerHeadline,\n  footerHeadlineAccent,\n  footerCta{ label, href },\n  exploreTitle,\n  exploreLinks[]{ label, href, target, rel },\n  socials[]{ platform, href, label },\n  newsletterTitle,\n  newsletterLabel,\n  newsletterPlaceholder,\n  newsletterSubmitLabel,\n  newsletterRequiredMessage,\n  newsletterInvalidMessage,\n  copyright,\n  legalLinks[]{ label, href, target, rel },\n\n  siteName,\n  siteUrl,\n  defaultTitle,\n  titleTemplate,\n  defaultDescription,\n  "ogImage": ogImage.asset->url,\n  "ogImageWidth": ogImage.asset->metadata.dimensions.width,\n  "ogImageHeight": ogImage.asset->metadata.dimensions.height,\n  ogImageAlt,\n  googleSiteVerification,\n\n  contactTitle,\n  contactMetaTitle,\n  contactMetaDescription,\n  contactFieldPlaceholders[]{ value, label },\n  contactSubjectLabel,\n  contactSubjectPlaceholder,\n  contactSubjectOptions[]{ value, label },\n  contactConsentText,\n  contactConsentLinkLabel,\n  contactConsentLinkHref,\n  contactSubmitLabel,\n  contactSuccessMessage,\n  contactMessagePlaceholder,\n  contactMarketingLabel,\n  contactTermsLabel,\n  contactValidationMessages[]{ value, label },\n\n  postListingTitle,\n  postListingHeading,\n  postListingDescription,\n\n  reportFormTitle,\n  reportFormSubmitLabel,\n  reportFormSuccessMessage,\n  reportFormPrivacyHref,\n  reportFormMarketingLabel,\n  reportFormConsentText,\n  reportFormConsentLinkLabel,\n  reportFormFieldLabels[]{ value, label },\n  reportFormValidationMessages[]{ value, label }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "testimonialsSection"][0]{\n  title,\n  categories,\n  testimonials[]{\n    "id": _key, category, audioSrc,\n    "imgSrc": image.asset->url, alt, quote, position\n  },\n  logos[]{ "id": _key, "src": logo.asset->url, alt }\n}': TESTIMONIALS_QUERY_RESULT;
  }
}
